

export const globalEntryLocations = [
    "Albuquerque Enrollment Center",
    "Anchorage Enrollment Center",
    "Atlanta International Global Entry EC",
    "Atlanta Port Office Global Entry Enrollment Center",
    "Austin-Bergstrom International Airport",
    "Baltimore Washington Thurgood Marshall Airport",
    "Blaine Global Entry Enrollment Center",
    "Boise Enrollment Center",
    "Boston-Logan Global Entry Enrollment Center",
    "Bradley International Airport Enrollment Center",
    "Brownsville Enrollment Center",
    "Buffalo-Ft. Erie Enrollment Center",
    "Calais Enrollment Center",
    "Calexico Enrollment Center",
    "Calgary Enrollment Center",
    "Champlain Enrollment Center",
    "Champlain GE Only",
    "Charlotte-Douglas International Airport",
    "Chicago Field Office Enrollment Center",
    "Chicago O'Hare International Global Entry EC",
    "Cincinnati Enrollment Center",
    "Cleveland U.S. Customs and border protection",
    "Dallas-Fort Worth International Airport Global Entry",
    "Dayton Enrollment Center",
    "Del Rio Enrollment Center",
    "Denver International Airport",
    "Derby Line Enrollment Center",
    "Des Moines GE Enrollment Center",
    "Detroit Enrollment Center Global Entry",
    "Detroit Metro Airport",
    "Doha International Airport",
    "Douglas Enrollment Center",
    "Eagle Pass",
    "Edmonton Enrollment Center",
    "El Paso Enrollment Center",
    "Fairbanks Enrollment Center",
    "Fort Lauderdale Global Entry Enrollment Center",
    "Fort Lauderdale International Airport Terminal",
    "Grand Forks, ND Enrollment Event",
    "Grand Forks, ND enrollment Center",
    "Grand Portage",
    "Guam International Airport",
    "Gulfport-Biloxi Global Entry Enrollment Center",
    "Halifax Enrollment Center",
    "Hidalgo Enrollment Center",
    "Honolulu Enrollment Center",
    "Houlton POE/Woodstock",
    "Houston Hobby Airport Enrollment Center",
    "Houston Intercontinental Global Entry EC",
    "Huntsville Global Entry Enrollment Center",
    "International Falls Global Entry Enrollment Center",
    "JFK International Global Entry EC",
    "Kansas City Enrollment Center",
    "Lansdowne, ON",
    "Laredo Enrollment Center",
    "Las Vegas Enrollment Center",
    "Los Angeles -Long Beach Seaport",
    "Los Angeles International Global Entry EC",
    "Memphis Intl Airport Global Enrollment Center",
    "Miami International Airport",
    "Milwaukee Enrollment Center",
    "Minneapolis - St. Paul Global Entry EC",
    "Mobile Regional Airport Enrollment Center",
    "Moline Quad Cities International Airport",
    "Montreal Enrollment Center",
    "Nashville Enrollment Center",
    "New Orleans Enrollment Center",
    "Newark Liberty Intl Airport",
    "Niagara Falls Enrollment Center",
    "Niagara Falls GE Only",
    "Nogales, AZ",
    "Omaha, NE Enrollment Center",
    "Orlando International Airport",
    "Ottawa International Airport",
    "Pembina Global Entry Enrollment Center",
    "Peoria international airport",
    "Philadelphia International Airport",
    "Phoenix Sky Harbor Global Entry Enrollment Center",
    "Pittsburgh International Airport",
    "Port Clinton, Ohio Enrollment Center",
    "Port Huron Enrollment Center",
    "Portland, OR Enrollment Center",
    "Richmond, VA Enrollment Center",
    "Rockford-Chicago International Airport",
    "SEAFO - Billings-Logan Airport GE Mobile Event",
    "SEAFO - Bozeman Airport",
    "SEAFO - FARGO Global Entry Workshop",
    "SEAFO - Missoula International Airport",
    "Salt Lake City International Airport",
    "San Antonio International Airport",
    "San Diego -Otay Mesa Enrollment Center",
    "San Francisco Global Entry Enrollment Center",
    "San Juan Global Entry Enrollment Center",
    "San Luis Enrollment Center",
    "Sanford Global Entry Enrollment Center",
    "Sault Ste Marie Enrollment Center",
    "Seatac International Airport Global Entry EC",
    "Singapore (Singapore, U.S. Embassy)",
    "South Bend Enrollment Center",
    "Springfield – Branson National Airport, MO",
    "St. Louis Enrollment Center",
    "Sweetgrass Global Entry Enrollment Center",
    "Sweetgrass NEXUS and FAST Enrollment Center",
    "Tampa Enrollment Center",
    "Toronto Enrollment Center",
    "Treasure Coast International Airport",
    "Tri-cities Enrollment Center",
    "Tucson Enrollment Center",
    "U.s. Custom House - Bowling Green",
    "Vancouver Enrollment Center",
    "Vancouver Urban Enrollment Center",
    "Warroad Enrollment Center",
    "Warwick, RI Enrollment Center",
    "Washington Dulles International Global Entry EC",
    "Washington, DC Enrollment Center",
    "West Palm Beach Enrollment Center",
    "Winnipeg Enrollment Center",
];
